name: test after deploy
on: 
  release:
    types: [published]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Audit github page deployment
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://bradtaniguchi.github.io/fcc-markdown-previewer#/
          # budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report